export const styleProps = {
  formContainer: {
    width: "100%",
    maxWidth: "100%",
    overflow: "auto",
    margin: "20px",
    padding: "5px",
    animation: "fadeIn 0.5s ease-in-out",
  },
  heading: {
    textAlign: "center",
    color: "#000000",
    marginBottom: "10px",
  },
  form: {
    backgroundColor: "white",
    padding: "10px",
    borderRadius: "8px",
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
    width: "100%",
    maxWidth: "800px",
    margin: "0 auto",
  },
  inputField: {
    inputContainer: {
      marginBottom: "30px",
    },
    label: {
      display: "block",
      marginBottom: "5px",
      fontWeight: "bold",
      color: "#333",
    },
    input: {
      width: "100%",
      padding: "12px",
      height: "40px",
      border: "2px solid #ccc",
      boxSizing: "border-box",
      borderRadius: "4px",
      transition: "border-color 0.3s",
      fontSize: "18px",
    },
  },
  textAreaField: {
    inputContainer: {
      marginBottom: "30px",
    },
    label: {
      display: "block",
      marginBottom: "5px",
      fontWeight: "bold",
      color: "#333",
    },
    textArea: {
      resize: "none",
      width: "100%",
      padding: "12px",
      height: "250px",
      border: "2px solid #ccc",
      borderRadius: "4px",
      transition: "border-color 0.3s",
      marginBottom: "10px",
      boxSizing: "border-box",
      fontSize: "18px",
    },
  },
  submitButton: {
    display: "block",
    width: "100%",
    backgroundColor: "#4caf50",
    color: "white",
    marginTop: "20px",
    padding: "12px 20px",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    transition: "background-color 0.3s",
  },
};
